const type0 = {
  html: `<h4 class="accesshide">Текст вопроса</h4><input type="hidden" name="q848480:12_:sequencecheck" value="1"><div class="qtext"><p>При решении задачи перечисления в комбинаторном анализе:</p></div><div class="ablock no-overflow visual-scroll-x"><div class="prompt">Выберите один или несколько ответов:</div><div class="answer"><div class="r0"><input type="hidden" name="q848480:12_choice0" value="0"><input type="checkbox" name="q848480:12_choice0" value="1" id="q848480:12_choice0" aria-labelledby="q848480:12_choice0_label"><div class="d-flex w-auto" id="q848480:12_choice0_label" data-region="answer-label"><div class="flex-fill ml-1"><p>в соединениях используются элементы несчётных множеств</p></div></div> </div>
    <div class="r1"><input type="hidden" name="q848480:12_choice1" value="0"><input type="checkbox" name="q848480:12_choice1" value="1" id="q848480:12_choice1" aria-labelledby="q848480:12_choice1_label"><div class="d-flex w-auto" id="q848480:12_choice1_label" data-region="answer-label"><div class="flex-fill ml-1"><p>составляемые соединения содержат несчётное множество элементов</p></div></div> </div>
    <div class="r0"><input type="hidden" name="q848480:12_choice2" value="0"><input type="checkbox" name="q848480:12_choice2" value="1" id="q848480:12_choice2" aria-labelledby="q848480:12_choice2_label"><div class="d-flex w-auto" id="q848480:12_choice2_label" data-region="answer-label"><div class="flex-fill ml-1"><p>составляемые соединения содержат конечное число элементов</p></div></div> </div>
    <div class="r1"><input type="hidden" name="q848480:12_choice3" value="0"><input type="checkbox" name="q848480:12_choice3" value="1" id="q848480:12_choice3" aria-labelledby="q848480:12_choice3_label"><div class="d-flex w-auto" id="q848480:12_choice3_label" data-region="answer-label"><div class="flex-fill ml-1"><p>применяются основные комбинаторные понятия</p></div></div> </div>
    <div class="r0"><input type="hidden" name="q848480:12_choice4" value="0"><input type="checkbox" name="q848480:12_choice4" value="1" id="q848480:12_choice4" aria-labelledby="q848480:12_choice4_label"><div class="d-flex w-auto" id="q848480:12_choice4_label" data-region="answer-label"><div class="flex-fill ml-1"><p>могут применяться правило суммы и правило произведения</p></div></div> </div>
    </div></div>`,
  jsonAnswer: `[{"checked":true,"value":"в соединениях используются элементы несчётных множеств"},{"checked":true,"value":"составляемые соединения содержат несчётное множество элементов"},{"checked":true,"value":"составляемые соединения содержат конечное число элементов"},{"checked":true,"value":"применяются основные комбинаторные понятия"},{"checked":true,"value":"могут применяться правило суммы и правило произведения"}]`,
  question_hash: '123456',
  question_type: 0,
};
const type1 = {
  html: `<h4 class="accesshide">Текст вопроса</h4><input type="hidden" name="q848480:2_:sequencecheck" value="1"><div class="qtext"><p>Соответствие между видом чисел и их количеством:</p><p>Даны цифры 1, 2, 3, 4, 5. Тогда:</p></div><div class="ablock"><table class="answer"><tbody><tr class="r0"><td class="text"><p>количество всех возможных нечётных трёхзначных чисел, все цифры
        в записи которых различны, равно</p></td><td class="control"><label class="accesshide" for="menuq848480:2_sub0">Ответ 1</label><select class="select custom-select custom-select ml-1" id="menuq848480:2_sub0" name="q848480:2_sub0"><option selected="selected" value="0">Выберите...</option><option value="1">48</option><option value="2">90</option><option value="3">25</option><option value="4">36</option><option value="5">50</option></select> </td></tr><tr class="r1"><td class="text"><p>количество всех возможных чётных трёхзначных чисел равно</p></td><td class="control"><label class="accesshide" for="menuq848480:2_sub1">Ответ 2</label><select class="select custom-select custom-select ml-1" id="menuq848480:2_sub1" name="q848480:2_sub1"><option selected="selected" value="0">Выберите...</option><option value="1">48</option><option value="2">90</option><option value="3">25</option><option value="4">36</option><option value="5">50</option></select> </td></tr><tr class="r0"><td class="text"><p>количество четырёхзначных чисел, больших 3000 и все цифры в записи
        которых различны, равно</p></td><td class="control"><label class="accesshide" for="menuq848480:2_sub2">Ответ 3</label><select class="select custom-select custom-select ml-1" id="menuq848480:2_sub2" name="q848480:2_sub2"><option selected="selected" value="0">Выберите...</option><option value="1">48</option><option value="2">90</option><option value="3">25</option><option value="4">36</option><option value="5">50</option></select> </td></tr><tr class="r1"><td class="text"><p>количество всех трёхзначных чисел, меньших 200, равно</p></td><td class="control"><label class="accesshide" for="menuq848480:2_sub3">Ответ 4</label><select class="select custom-select custom-select ml-1" id="menuq848480:2_sub3" name="q848480:2_sub3"><option selected="selected" value="0">Выберите...</option><option value="1">48</option><option value="2">90</option><option value="3">25</option><option value="4">36</option><option value="5">50</option></select> </td></tr></tbody></table></div>`,
  jsonAnswer: `[{"text":"количество всех возможных нечётных трёхзначных чисел, все цифры\nв записи которых различны, равно","value":"25"},{"text":"количество всех возможных чётных трёхзначных чисел равно","value":"25"},{"text":"количество четырёхзначных чисел, больших 3000 и все цифры в записи\nкоторых различны, равно","value":"90"},{"text":"количество всех трёхзначных чисел, меньших 200, равно","value":"25"}]`,
  question_hash: '123456',
  question_type: 1,
};
const type2 = {
  html: `<h4 class="accesshide">Текст вопроса</h4><input type="hidden" name="q848480:8_:sequencecheck" value="2"><div class="qtext"><p>Переставляя цифры в числе 222555, какое количество можно получить
        различных шестизначных чисел:</p></div><div class="ablock no-overflow visual-scroll-x"><div class="prompt">Выберите один ответ:</div><div class="answer"><div class="r0"><input type="radio" name="q848480:8_answer" value="0" id="q848480:8_answer0" aria-labelledby="q848480:8_answer0_label"><div class="d-flex w-auto" id="q848480:8_answer0_label" data-region="answer-label"><div class="flex-fill ml-1"><p>100</p></div></div> </div>
        <div class="r1"><input type="radio" name="q848480:8_answer" value="1" id="q848480:8_answer1" aria-labelledby="q848480:8_answer1_label" checked="checked"><div class="d-flex w-auto" id="q848480:8_answer1_label" data-region="answer-label"><div class="flex-fill ml-1"><p>120</p></div></div> </div>
        <div class="r0"><input type="radio" name="q848480:8_answer" value="2" id="q848480:8_answer2" aria-labelledby="q848480:8_answer2_label"><div class="d-flex w-auto" id="q848480:8_answer2_label" data-region="answer-label"><div class="flex-fill ml-1"><p>15</p></div></div> </div>
        <div class="r1"><input type="radio" name="q848480:8_answer" value="3" id="q848480:8_answer3" aria-labelledby="q848480:8_answer3_label"><div class="d-flex w-auto" id="q848480:8_answer3_label" data-region="answer-label"><div class="flex-fill ml-1"><p>20</p></div></div> </div>
        <div class="r0"><input type="radio" name="q848480:8_answer" value="4" id="q848480:8_answer4" aria-labelledby="q848480:8_answer4_label"><div class="d-flex w-auto" id="q848480:8_answer4_label" data-region="answer-label"><div class="flex-fill ml-1"><p>60</p></div></div> </div>
        </div><div id="q848480:8_clearchoice" class="qtype_multichoice_clearchoice"><input type="radio" name="q848480:8_answer" id="q848480:8_answer-1" value="-1" class="sr-only" aria-hidden="true"><label for="q848480:8_answer-1"><a tabindex="0" role="button" class="btn btn-link ml-3 mt-n1 mb-n1" href="#">Очистить мой выбор</a></label></div></div>`,
  jsonAnswer: `[{"checked":false,"value":"100"},{"checked":false,"value":"120"},{"checked":true,"value":"15"},{"checked":false,"value":"20"},{"checked":false,"value":"60"}]`,
  question_hash: '123456',
  question_type: 2,
};
const type3 = {
  html: `<h4 class="accesshide">Текст вопроса</h4><input type="hidden" name="q848480:1_:sequencecheck" value="1"><div class="qtext"><p>9 молодых специалистов распределяются на три предприятия так,
        чтобы на одно предприятие быть направлены 3 специалиста, а на другое – 5, а на оставшееся
        – 1. Сколькими способами это можно сделать:</p></div><div class="ablock form-inline"><label for="q848480:1_answer">Ответ: <span class="answer"><input type="text" name="q848480:1_answer" id="q848480:1_answer" size="80" class="form-control d-inline"></span></label></div>`,
  jsonAnswer: `{"text":"Это можно сделать 81 способами."}`,
  question_hash: '123456',
  question_type: 3,
};

export const questions = [type0, type1, type2, type3];
